//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adress
    {
        public Adress()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int id_adress { get; set; }
        public string AdressName { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
    }
}
