//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int id_product { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> id_manufacturer { get; set; }
        public Nullable<int> id_suplier { get; set; }
        public Nullable<int> id_category { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> id_unit { get; set; }
        public Nullable<byte> Discount { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public string Article { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual Suplier Suplier { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
